import React from 'react'
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from '@/components/ui/button'
import { SessionDetail } from '../medical-agent/[sessionId]/page'
import moment from 'moment'
import jsPDF from "jspdf"

type props = {
    record: SessionDetail
}

function ViewReportDialog({ record }: props) {

    const handleDownloadPDF = () => {
        const doc = new jsPDF();

        // Title
        doc.setFontSize(16);
        doc.text("🩺 Medical AI Voice Agent Report", 20, 20);

        // Session Info
        doc.setFontSize(12);
        doc.text("Session Info:", 20, 35);
        doc.text(`Doctor: ${record?.selectedDoctor?.specialist || "Not specified"}`, 20, 45);
        doc.text(`User: user`, 20, 55);
        doc.text(`Consulted On: ${moment(new Date(record?.createdOn)).format("MMMM Do YYYY, h:mm a")}`, 20, 65);
        doc.text(`Agent: ${record?.selectedDoctor?.specialist || "AI Assistant"}`, 20, 75);

        // Chief Complaint
        doc.text("Chief Complaint:", 20, 90);
        doc.text((record?.report as any)?.chiefComplaint || "Not provided", 20, 100);

        // Summary
        doc.text("Summary:", 20, 115);
        doc.text((record?.report as any)?.summary || "No summary available", 20, 125);

        // Symptoms
        doc.text("Symptoms:", 20, 140);
        const symptoms = (record?.report as any)?.symptoms || [];
        if (symptoms.length > 0) {
            symptoms.forEach((s: string, i: number) => {
                doc.text(`- ${s}`, 25, 150 + (i * 10));
            });
        } else {
            doc.text("Not specified", 20, 150);
        }

        // Duration & Severity
        let offset = symptoms.length > 0 ? 150 + (symptoms.length * 10) : 160;
        doc.text("Duration & Severity:", 20, offset);
        doc.text(`Duration: ${(record?.report as any)?.duration || "Not specified"}`, 20, offset + 10);
        doc.text(`Severity: ${(record?.report as any)?.severity || "Not specified"}`, 20, offset + 20);

        // Footer
        doc.setFontSize(10);
        doc.text("This report was generated by an AI Medical Assistant for informational purposes only.", 20, offset + 40);

        // Save as PDF
        doc.save(`Medical_Report_${moment(new Date(record?.createdOn)).format("YYYYMMDD_HHmm")}.pdf`);


        // Medications Mentioned
        offset += 40;
        doc.text("Medications Mentioned:", 20, offset);
        const medications = (record?.report as any)?.medicationsMentioned || [];
        if (medications.length > 0) {
            medications.forEach((m: string, i: number) => {
                doc.text(`- ${m}`, 25, offset + 10 + (i * 10));
            });
        } else {
            doc.text("Not mentioned", 20, offset + 10);
        }

    };

    return (
        <Dialog>
            <DialogTrigger>
                <Button variant="link" size="sm">View Report</Button>
            </DialogTrigger>
            <DialogContent className="w-[90vw] h-[95vh] max-w-none overflow-y-auto rounded-none">
                <DialogHeader>
                    <DialogTitle asChild>
                        <h2 className="font-bold text-center text-xl text-blue-500">
                            🩺 Medical AI Voice Agent Report
                        </h2>
                    </DialogTitle>
                    <DialogDescription asChild>
                        <div className="mt-6 space-y-6">

                            {/* Session Info */}
                            <div>
                                <h2 className="font-bold text-blue-500 text-lg">Session Info</h2>
                                <div className="grid grid-cols-2 gap-2 mt-2 text-sm">
                                    <p><span className="font-bold">Doctor:</span> {record?.selectedDoctor?.specialist || "Not specified"}</p>
                                    <p><span className="font-bold">User:</span> user</p>
                                    <p><span className="font-bold">Consulted On:</span> {moment(new Date(record?.createdOn)).format("MMMM Do YYYY, h:mm a")}</p>
                                    <p><span className="font-bold">Agent:</span> {record?.selectedDoctor?.specialist || "AI Assistant"}</p>
                                </div>
                            </div>

                            {/* Chief Complaint */}
                            <div>
                                <h2 className="font-bold text-blue-500 text-lg">Chief Complaint</h2>
                                <p className="text-sm mt-1 text-gray-700">
                                    {(record?.report as any)?.chiefComplaint || "The user did not clearly state a chief complaint in this initial interaction."}
                                </p>
                            </div>

                            {/* Summary */}
                            <div>
                                <h2 className="font-bold text-blue-500 text-lg">Summary</h2>
                                <p className="text-sm mt-1 text-gray-700">
                                    {(record?.report as any)?.summary || "No summary available."}
                                </p>
                            </div>

                            {/* Symptoms */}
                            <div>
                                <h2 className="font-bold text-blue-500 text-lg">Symptoms</h2>
                                {((record?.report as any)?.symptoms || []).length > 0 ? (
                                    <ul className="list-disc pl-6 text-sm text-gray-700">
                                        {(record?.report as any).symptoms.map((s: string, i: number) => (
                                            <li key={i}>{s}</li>
                                        ))}
                                    </ul>
                                ) : (
                                    <p className="text-sm text-gray-700">Not specified</p>
                                )}
                            </div>

                            {/* Duration & Severity */}
                            <div>
                                <h2 className="font-bold text-blue-500 text-lg">Duration & Severity</h2>
                                <div className="grid grid-cols-2 gap-2 text-sm mt-1">
                                    <p><span className="font-bold">Duration:</span> {(record?.report as any)?.duration || "Not specified"}</p>
                                    <p><span className="font-bold">Severity:</span> {(record?.report as any)?.severity || "Not specified"}</p>
                                </div>
                            </div>

                            {/* Medications Mentioned */}
                            <div>
                                <h2 className="font-bold text-blue-500 text-lg">Medications Mentioned</h2>
                                {((record?.report as any)?.medicationsMentioned || []).length > 0 ? (
                                    <ul className="list-disc pl-6 text-sm text-gray-700">
                                        {(record?.report as any).medicationsMentioned.map((m: string, i: number) => (
                                            <li key={i}>{m}</li>
                                        ))}
                                    </ul>
                                ) : (
                                    <p className="text-sm text-gray-700">Not mentioned</p>
                                )}
                            </div>


                            {/* Download Button */}
                            <div className="flex justify-center pt-4">
                                <Button onClick={handleDownloadPDF} variant="default" size="sm">
                                    Download PDF
                                </Button>
                            </div>

                            {/* Footer Note */}
                            <p className="text-xs text-gray-500 text-center">
                                This report was generated by an AI Medical Assistant for informational purposes only.
                            </p>
                        </div>
                    </DialogDescription>
                </DialogHeader>
            </DialogContent>
        </Dialog>
    )
}

export default ViewReportDialog
